apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-backup
  namespace: mongodb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: backup-volume 
  storageClassName: hostpath