apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: mongodb
spec:
  schedule: "0 * * * *" # executes job every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "mongodb-backup"
            image: "mongodb-demo-backup:1.0.2"
            imagePullPolicy: Never
            envFrom:
              - secretRef:
                  name: mongodb-backup
            volumeMounts:
              - mountPath: /mnt/backup
                name: backup-volume
          restartPolicy: Never
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: "datadir-mongodb-backup"
            
                