apiVersion: v1
kind: Pod
metadata:
  name: mongodb-demo-app
  namespace: mongodb
spec:
  containers:
    - name: mongodb-demo-app
      image: mongodb-demo-app:1.0.3
      envFrom:
        - secretRef:
            name: mongodb-demo-app
      ports:
        - containerPort: 27017
